title: kim thang thang blog
email: lyoungh2570@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':categories/:title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lyoungh.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: kim thang thang # add your name
author-pic: telescope.jpg
about-author: Kim thang thang

# Contact links
email: lyoungh2570@gmail.com
phone: 01033612519
website: "lyoungh.github.io"# Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: lyoungh # Add your Github handle
twitter: '@artemsheludko_' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: kim-thangthangs-blog # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
pagination:
  enabled: true
  per_page: 2
  limit: 0
  sort_field: "date"
  sort_reverse: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
